apiVersion: apps/v1
kind: Deployment
metadata:
  name: moco-controller
  namespace: moco-system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: moco-controller
        image: ghcr.io/masa213f/moco-issue-419:controller
        imagePullPolicy: Always
        args:
        - --check-interval=10s
