apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 10
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: ghcr.io/masa213f/moco-issue-419:case1-client
        imagePullPolicy: Always
        name: client
        args:
        - "-r"
        - "100"
      securityContext:
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 10000
        runAsUser: 10000
