name: Build
on:
  workflow_dispatch:
jobs:
  image:
    name: Push Container Image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Login to ghcr.io
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Build images
      run: docker build -t client:dev .
    - name: Push images
      run: |
        SUFFIX=$(date "+%Y%m%d%H%M%S")
        docker tag client:dev ghcr.io/masa213f/moco-issue-419:client-${SUFFIX}
        docker push ghcr.io/masa213f/moco-issue-419:client-${SUFFIX}
        docker tag client:dev ghcr.io/masa213f/moco-issue-419:client
        docker push ghcr.io/masa213f/moco-issue-419:client
